version: 2

models:

  # =====================================
  #  DIMENSIONS
  # =====================================

  - name: dim_customers
    description: "Customer dimension"
    config:
      materialized: table
    columns:
      - name: customer_pk
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null

  - name: dim_products
    description: "Product dimension"
    config:
      materialized: table
    columns:
      - name: product_pk
        tests:
          - unique
          - not_null
      - name: product_id
        tests:
          - not_null

  - name: dim_employees
    description: "Employee dimension"
    config:
      materialized: table
    columns:
      - name: employee_pk
        tests:
          - unique
          - not_null
      - name: employee_id
        tests:
          - not_null

  - name: dim_categories
    description: "Product categories dimension"
    config:
      materialized: table
    columns:
      - name: category_pk
        tests:
          - unique
          - not_null
      - name: category_id
        tests:
          - not_null

  - name: dim_suppliers
    description: "Suppliers dimension"
    config:
      materialized: table
    columns:
      - name: supplier_pk
        tests:
          - unique
          - not_null
      - name: supplier_id
        tests:
          - not_null

  # =====================================
  #  FACTS
  # =====================================

  - name: fct_orders
    description: "Fact table for customer orders (line-level)"
    config:
      materialized: table
    columns:
      - name: order_pk
        tests:
          - not_null     # ❗ تمت إزالة UNIQUE هنا

      - name: customer_pk
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_pk

      - name: product_pk
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_pk

      - name: total_order_value
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric

      - name: order_status_flag
        tests:
          - accepted_values:
              arguments:
                values: ['Shipped', 'Pending', 'Cancelled']

  - name: fct_order_details
    description: "Fact table at line-item level"
    config:
      materialized: table
    columns:
      - name: order_detail_pk
        tests:
          - unique
          - not_null

      - name: order_pk
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_pk

      - name: product_pk
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_pk

      - name: customer_pk
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_pk

      - name: employee_pk
        tests:
          - relationships:
              to: ref('dim_employees')
              field: employee_pk

      - name: extended_price
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
